# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc64789be447c281ab1b742e93e90491469a8de0e168dea96cdf6c26570eb1d3af159f71afd288cce29661357a9943dfb06f49f31c114a39fe3a6c0f3edd972
  mail_address: <%= ENV["MAILADDRESS"] %>
  mail_pass: <%= ENV["MAILPASS"] %>

test:
  secret_key_base: 883ecde208abe7288843056008669321c2159ecebd2e829b098ebb077c455abca8484fb3848ccaf37d7fed69bdbd1304505a02089b0d89c40a5a027fb554ebf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail_address: <%= ENV["MAILADDRESS"] %>
  mail_pass: <%= ENV["MAILPASS"] %>R
